# SITE CONFIGURATION
title: Luisa T. Schneider # your site title
author: Luisa Schneider # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ltschneider.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Luisa Schneider
  links:
    - https://twitter.com/lt_schneider
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/luisa-t-schneider-2b574777
    - https://plus.google.com/+BenBalter
    - https://github.com/LtSchneider
    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Publications', link: '/list-of-publications'}
  - {name: 'Research', link: '/research'}

tagline: >
  Anthropologist and Research Consultant

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: your-email@domain.com # email for form submission

twitter_username: lt_schneider # replace with your_twitter_username or comment to remove link from footer
github_username:  LtSchneider # replace with your_github_username or comment to remove link from footer
instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: none # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
